version: "3"

services:
  #   prometheus:
  #     depends_on:
  #       - evmos-devnet
  #       # - cadvisor
  #     image: prom/prometheus:v2.36.2
  #     volumes:
  #       - ./prometheus/:/etc/prometheus/
  #       - prometheus_data:/prometheus
  #     command:
  #       - '--config.file=/etc/prometheus/prometheus.yml'
  #       - '--storage.tsdb.path=/prometheus'
  #       - '--web.console.libraries=/usr/share/prometheus/console_libraries'
  #       - '--web.console.templates=/usr/share/prometheus/consoles'
  #     ports:
  #       - 9090:9090
  #     networks:
  #       - back-tier
  #     restart: always

  # graphite:
  #   image: graphiteapp/graphite-statsd:latest
  #   container_name: graphite
  #   ports:
  #     - 80:80
  #     - 2003:2003
  #     - 8125:8125
  #   volumes:
  #     - ./storage:/opt/graphite/storage
  #   environment:
  #     - COLLECTD=1
  #   networks:
  #     - back-tier

  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   container_name: cadvisor
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   networks:
  #     - back-tier
  #   restart: always


  # remotestorageadapter:
  #   image: remote-storage-adapter
  #   container_name: remote-storage-adapter
  #   build: ./remote-storage-adapter
  #   restart: always
  #   ports:
  #     - 9201:9201
  #   networks:
  #     - back-tier

  evmos-devnet:
    image: evmos-devnet
    build: ./evmos-devnet
    restart: always
    ports:
      - 8545:8545
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:26657/status" ]
      interval: 30s
      timeout: 10s
      retries: 5

  tx-bot:
    image: vhomsi/tx-bot
    ports:
      - 8081:8080
    depends_on:
      - evmos-devnet
    environment:
      - ORCH_PRIV_KEY=0x1c384b3fb9a1cff8caee1e2d078bb9bc28a542dcc7ac779a445dc68b3dc2fe1f
      - RPC_URL=http://evmos-devnet:8545
    restart: always

networks:
  default:
    external:
      name: back-tier
