version: "3"

networks:
  front-tier:
  back-tier:


volumes:
  prometheus_data:
  grafana_data:
  devnet_data:


services:
  prometheus:
    depends_on:
      - evmos-devnet
      # - cadvisor
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always

  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   container_name: cadvisor
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   networks:
  #     - back-tier
  #   restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
      - evmos-devnet
    ports:
      - 8000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always

  evmos-devnet:
    image: evmos-devnet
    build: ./evmos-devnet
    restart: always
    networks:
      - back-tier
    ports:
      - 8545:8545
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:26657/status"]
        interval: 30s
        timeout: 10s
        retries: 5

  tx-bot:
    image: vhomsi/tx-bot
    ports:
      - 8081:8080
    depends_on:
      - evmos-devnet
    networks:
      - back-tier
    environment:
      - ORCH_PRIV_KEY=0x1c384b3fb9a1cff8caee1e2d078bb9bc28a542dcc7ac779a445dc68b3dc2fe1f
      - RPC_URL=http://evmos-devnet:8545
    restart: always
