# my global config
global:
  scrape_interval: 1s # By default, scrape targets every 1 second
  evaluation_interval: 1s # By default, scrape targets every 1 second

# remote_write:
#   - url: "http://remote-storage-adapter:9201/write"

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ["localhost:9090"]

  # - job_name: "cadvisor"
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ["cadvisor:8080"]

  - job_name: "evmos-tendermint"
    scrape_interval: 1s
    static_configs:
      - targets: ["evmos-devnet:26660"]

  - job_name: "evmos-rpc"
    scrape_interval: 1s
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["evmos-devnet:6065"]

  - job_name: "tx-bot"
    scrape_interval: 1s
    static_configs:
      - targets: ["tx-bot:8080"]
